packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  better-sqlite3: true
  "@swc/core": true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  xxhash-addon: true
  nx: set this to true or false

blockExoticSubdeps: false

onlyBuiltDependencies:
  - esbuild
  - lightningcss
