packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  xxhash-addon: true
  sharp: true
  vue-demi: true
  '@bufbuild/buf': true
  '@parcel/watcher': true

blockExoticSubdeps: false
autoDedupe: true