// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"tgb-resolver/server-go/features/realtime"
	"tgb-resolver/server-go/features/shared/config"
	"tgb-resolver/server-go/features/show"
)

// Injectors from wire.go:

func initApp(cfg *config.Config) (*App, func(), error) {
	db, cleanup, err := provideDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	store := show.NewStore(db)
	clock := provideClock()
	hub := realtime.NewHub(clock)
	fileStore := provideBlobs(cfg)
	service := show.NewService(store, hub, clock, fileStore)
	app := NewApp(cfg, db, store, service, hub, clock, fileStore)
	return app, func() {
		cleanup()
	}, nil
}
