<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TGB.Resolver.Server</RootNamespace>
    <BaseIntermediateOutputPath>obj/</BaseIntermediateOutputPath>
    <OpenApiDocumentPath>$(MSBuildProjectDirectory)/openapi.yaml</OpenApiDocumentPath>
    <GenerateOpenApiDocument>false</GenerateOpenApiDocument>
    <StaticWebAssetDevelopmentManifestPath>$(MSBuildProjectDirectory)/obj/$(Configuration)/$(TargetFramework)/staticwebassets.development.json</StaticWebAssetDevelopmentManifestPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.3.0" />
    <PackageReference Include="FastEndpoints.Swagger" Version="8.3.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="GTweens" Version="4.0.0" />
    <PackageReference Include="Haukcode.ArtNet" Version="4.0.106" />
    <PackageReference Include="Haukcode.HighResolutionTimer" Version="1.4.73" />
    <PackageReference Include="Haukcode.sACN" Version="2.0.104" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
    <PackageReference Include="NodaTime" Version="3.3.3" />
    <!-- Temporary workaround until vulnerability fixed: https://github.com/dotnet/efcore/issues/38257 -->
    <!-- The issue itself is closed, but WTH, the bundled version is still vulnerable??? -->
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" VersionOverride="3.0.3">
      <Version>3.0.5</Version>
    </PackageReference>
    <PackageReference Include="NSwag.AspNetCore" Version="14.7.1" />
    <PackageReference Include="NSwag.MSBuild" Version="14.7.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.20" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.11" />
    <PackageReference Include="TypedSignalR.Client.TypeScript.Attributes" Version="1.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TGB.Resolver.IcpcXmlParser\TGB.Resolver.IcpcXmlParser.csproj" />
  </ItemGroup>

  <Target Name="GenerateOpenApiDocumentTarget" AfterTargets="Build" Condition="'$(DesignTimeBuild)' != 'true' and '$(GenerateOpenApiDocument)' == 'true'">
    <Exec WorkingDirectory="$(ProjectDir)" Command="$(NSwagExe_Net100) aspnetcore2openapi /project:$(MSBuildProjectFullPath) /documentName:v1 /output:$(OpenApiDocumentPath) /noBuild:true" />
  </Target>

</Project>
