<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>TGB.Resolver.IcpcXmlParser</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TypedSignalR.Client.TypeScript.Attributes" Version="1.17.0" />
  </ItemGroup>

</Project>
